source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

pod 'Masonry' ,'0.5.3'
pod 'AVOSCloud'
pod 'DZNSegmentedControl'
pod 'ReactiveCocoa', '~> 2.5'
pod 'GCPlaceholderTextView', '~> 1.0.1'
pod 'libPhoneNumber-iOS', '~> 0.8'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'AFViewShaker', '~> 0.0.2'
pod 'UICountingLabel'
pod 'MJRefresh'
pod 'FXBlurView', '~> 1.6.4'
pod 'UMengAnalytics'
pod 'Fabric'
pod 'Crashlytics'
pod 'AFSoundManager'
pod 'SDWebImage', '~> 3.7.3'
pod 'LeanCloudFeedback'
pod 'JDStatusBarNotification'
pod 'TTTAttributedLabel'


